name: Deploy MyData Backend Application

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 배포

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. GitHub에서 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew build

      # 4. Build 파일을 압축하여 S3로 업로드
      - name: Zip build files
        run: zip -r build-mydata.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2 

      # 5. 빌드 파일을 S3에 업로드
      - name: Upload to S3
        run: |
          aws s3 cp build-mydata.zip s3://my-github-actions-s3-bucket-cicd/build-mydata.zip

      # 6. 새로운 CodeDeploy 애플리케이션으로 배포
      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name mydata-codedeploy-app \ 
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name mydata-codedeploy-deployment-group \ 
            --s3-location bucket=my-github-actions-s3-bucket-cicd,key=build-mydata.zip,bundleType=zip
